### ISSUE TITLE
Why .txt instead of .md in /manuscript/?

### ISSUE THREAD

**Issue by pdehaan** [DinisCruz/Book_Practical_Git#3]
**Question:** Why does the repo use /manuscript/*.txt files instead of .md? Switching to Markdown extension would make it easier to read in GitHub since it would render the markdown and show any possible formatting issues.

https://github.com/DinisCruz/Book_Practical_Git/blob/master/manuscript/addingfilestoteammentorswebrootviaauserdatafoldersyncedwithgithub-2.txt#L123-L124

**Comment by DinisCruz** [comment]
This conversion to markdown has been done with the latests changes
